[tool.black]
line-length = 100
skip-string-normalization = true

[tool.pytest.ini_options]
addopts = "--cov=/apps/*"
filterwarnings = [
    "ignore::django.utils.deprecation.RemovedInDjango41Warning"
]
