[tool.black]
line-length = 100
skip-string-normalization = true

[tool.pytest.ini_options]
addopts = [
    "--cov-config=.coveragerc",
    "--cov=apps/",
    "--cov-fail-under=100",
    "--ds=league_manager.settings.test",
]
filterwarnings = [
    "ignore:The USE_L10N setting is deprecated:",
    "ignore:ANTIALIAS is deprecated and will be removed in Pillow 10:",
]

[tool.coverage.run]
omit = [
    "*/apps.py",
    "*/migrations/*",
    "*/__init__.py",
    "*/tests/*",
    "*/urls.py",
]
