# Generated by Django 4.0.4 on 2022-05-28 07:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('goals', models.IntegerField()),
                ('host', models.BooleanField()),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, to='seasons.game'
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
