# Generated by Django 4.0.4 on 2022-06-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('seasons', '0002_gameteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTeamStandings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('points', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_lost', models.IntegerField(default=0)),
                (
                    'season',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='seasons.season'
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
                ),
            ],
        ),
    ]
