apiVersion: apps/v1
kind: Deployment
metadata:
  name: league-manager
  labels:
    app: league-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: league-manager
  template:
    metadata:
      labels:
        app: league-manager
    spec:
      containers:
        - name: league-manager-container
          imagePullPolicy: IfNotPresent
          image: web-k8s
          command: ['./start.sh']
          livenessProbe:
            httpGet:
              path: /admin/login/
              port: 8000
          ports:
          - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: 'league_manager.settings.development'

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: SECRET_KEY

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: league-manager-config
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: league-manager-config
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: league-manager-config
                  key: POSTGRES_PORT
            - name: POSTGRES_HOST
              value: postgres-service
