apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-container
spec:
  type: LoadBalancer
  selector:
    app: postgres-container
    tier: backend
  ports:
    - name: postgres-service
      protocol: TCP
      port: 5432
      targetPort: 5432
